### ISSUE TITLE
Semantic PR and conventional commits

### ISSUE THREAD

**Issue by manifestori** [bom-squad/protobom#50]
Hello there!

We all have diverse backgrounds, follow varying standards, and likely have differing opinions on managing this open-source project.

I suggest that we delegate those decisions so that we can spend more time developing "protobom." It would be best to adhere to well-accepted standards for commits, pull requests, and branch names.

I would like to suggest we do the following:

1.  Follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
2. Use either Github App or [Github Action](https://github.com/amannn/action-semantic-pull-request) for semantic pull request 
3. Use pre-commits hooks to ensure following those guidelines locally (before commit)
4. Use `-` as separators in branch names (`fix-some-error`)

looking forward to hearing your thoughts!

**Comment by jspeed-meyers** [comment]
@manifestori, fine with me, as long as you can commit to tutoring those of us who haven't adhered to conventional commit conventions in the past :)

**Comment by puerco** [comment]
I don't like conventional commits much :( I find that it steals valuable characters from the commit title but if folks prefer to use them I can certainly play along. I would prefer fostering a culture of atomic changes and clear human-readable descriptions when needed. I'm curious about the branch naming, what's the motivation there?

**Comment by manifestori** [comment]
It appears that you are correct about the limit of 72 characters (or 50 if following common standards) for commit names. However, I personally have not faced any issues with using longer commit names. In fact, in some projects, we have even included ticket numbers such as 'chore: do something [PRJ-000]'.

I fully support the idea of submitting atomic changes and providing clear, easy-to-understand descriptions, but that's very subjective when it comes down to formatting :) 

Another benefit of utilizing conventional commits is that it can be combined with a .goreleaser configuration, for example:
```yaml
changelog:
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
```

With this feature, change logs in Github Releases will be automatically ordered, sorted, and divided to the change, saving tons on manual work.

Regarding branch name, I'm fine with whatever, but we just need to figure out a style we want to follow, also, Github default squash commit tittle, follows the branch name and not the "first commit" or "pull request title", but we can change this.

A clean branch list is just better than a mixed branch list imho 🧹 
```
chore-ori-test
feat/my_branch
feat/manifestori-add-integeration-test
feat_add_integration_test
```

VS
```
chore-ori-test
feat-my-branch
feat-add-ingration-test
```

(not sure we need to attach branch owner to name, but its a convention in some OSS project)
